services:
  api: 
    build: ./app
    image: ml-api
    container_name: churn-api
    ports:
      - "8000:8000"
  ui:
    build: ./ui
    image: ml-ui
    container_name: churn-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
