# написать dockerfile для создания контейнера сервиса

# установка образа с нужной версией python
FROM python:3.12-slim

# установка рабочей директории
WORKDIR /app

# копирование файла зависимостей в контейнер
COPY requirements.txt .

# установка зависимостей без кеша
RUN pip install --no-cache-dir -r requirements.txt

# копирование файлов сервиса
COPY . .

# команда для запуска контейнера
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]